insert into fiber_festivals (name, location, website_url, years_in_operation, typical_months, fiber_focus, accepts_non_fiber, notes) values
  ('NH Sheep & Wool Festival', 'Deerfield, NH', 'https://nhswf.org', 'Est. 1994', 'May', 'Sheep & wool', 'Yes — jewelry and adjacent crafts welcome', 'Long-running festival at Deerfield Fairgrounds. Strong crochet/knitting vendor presence. Excellent fit for crochet jewelry and clothing.'),
  ('Massachusetts Sheep & Woolcraft Fair', 'Cummington, MA', null, 'Est. 1978', 'May', 'Sheep & wool', 'Yes — fiber-adjacent crafts accepted', 'One of the oldest sheep & wool fairs in NE. Held at Cummington Fairgrounds. Very fiber-focused audience.'),
  ('Maine Fiber Frolic', 'Windsor, ME', 'https://fiberfrolic.com', null, 'June', 'All fiber arts', 'Yes — crochet, knitting, jewelry welcome', 'Annual fiber arts festival in Windsor ME. Broad fiber focus including crochet. Strong buyer attendance from across New England.'),
  ('Vermont Sheep & Wool Festival', 'Tunbridge, VT', null, null, 'October', 'Sheep & wool', 'Check with organizers', 'Fall festival in Tunbridge, scenic foliage season backdrop. Smaller but dedicated fiber arts audience.'),
  ('CT Sheep, Wool & Fiber Festival', 'Vernon, CT', null, null, 'April', 'All fiber arts', 'Yes — fiber-adjacent crafts accepted', 'Annual spring festival in Vernon CT. Broad fiber arts focus. Good early-season market opportunity.'),
  ('Stitches East', 'Hartford, CT', 'https://stitcheseast.com', null, 'October', 'Knitting & crochet', 'Yes — crochet and wearable crafts primary focus', 'Large national knitting/crochet conference, held in Hartford CT when in NE. Marketplace draws serious fiber arts shoppers. Premium fit for crochet clothing and jewelry.'),
  ('WEBS Tent Sale & Fiber Event', 'Northampton, MA', 'https://www.yarn.com', null, 'June', 'All fiber arts', 'Check with organizers', 'Annual event at WEBS — Americas Yarn Store in Northampton MA. Huge fiber arts crowd. Investigate vendor opportunities around the event.')
on conflict (name) do nothing;
